### ISSUE TITLE
SATT product in renewal after failed order is not converted to sub

### ISSUE THREAD

**Issue by growdev** [Prospress/woocommerce-subscribe-all-the-things#102]
To reproduce:

- WC 2.6.14
- WCS 2.0.20
- STATT 1.1.2
- Add a subscription product to cart and checkout
- Our site is using Auth.net so I changed the Billing Zip code to `46282` per [this](https://developer.authorize.net/hello_world/testing_guide/)
- Force a renewal of the subscription
- The order fails and the subscription is placed On Hold
- Login as the customer and go to the `/my-account/subscriptions` page
- Select the On Hold subscription
- Press "Pay" next to the subscriptions failed renewal order
- On the checkout page notice that the subscription scheme is not added to the item

h/t to @javorszky for a similar fix in #68 

PR to follow

**Comment by javorszky** [comment]
The downside of this fix is that if the product's subscription option is discounted, it will be doubly discounted.

If the original price is $15, there's a 10% discount, the initial checkout will be $13.50.

If we're paying for a failed renewal order, that 10% discount gets applied to the $13.50, and it becomes $12.15, which is not ideal.

Any help would be appreciated @franticpsyx, if you have the time / ideas.

**Comment by franticpsyx** [comment]
@growdev @javorszky -- thanks for the report and feedback folks!

We are currently working on #42 and #96 which will introduce some architecture changes and WC 3.0 compatibility (could justify a bump to 2.0). I can definitely have a look at this as part of that refactor.

**Comment by javorszky** [comment]
Awesome, thank you :). I'll read those issues a wee bit later, they are loong. :D

**Comment by franticpsyx** [comment]
You might want to take a look at the `issue-42` branch directly. There's a lot of useful inline commentary there -- the commits should also allow you to understand the objective of the refactor.

I will open a PR to discuss the changes when I'm done refactoring the entire (small) codebase to utilize the new Product API.

**Comment by growdev** [comment]
Thanks for the info @franticpsyx !

**Comment by franticpsyx** [comment]
Merged the work done so far on #96 and #42 in the `2.0` branch. There are a number of issues that are being worked at the same time since the entire codebase is being re-written. Isolating each issue in a separate branch is impractical, but it should be fairly straightforward to follow what's happening - see https://github.com/Prospress/woocommerce-subscribe-all-the-things/compare/master...2.0

**Comment by franticpsyx** [comment]
This _should_ be resolved in `2.0`. Feel free to take that branch for a spin and post feedback!

**Comment by javorszky** [comment]
Hey @franticpsyx ! The 2.0 branch still does not solve the double-discount issue.

**Comment by javorszky** [comment]
Also, in our specific case we can't upgrade from Subs 2.0.20 because more things would break :/

**Comment by franticpsyx** [comment]
Hey, thanks for having a look @javorszky -- will have a look at this before v2 hits "beta".

**Comment by javorszky** [comment]
Hi @franticpsyx!

I've managed to sort of solve it for our project, though it's a bit hacky. I've had to do two things:

1. hook into `wcsatt_price_filters_allowed` when it's a renewal order (probably should do for resubscribes as well), because the order I'm paying already should have a discounted price. Setting this to false would prevent the double-discounts, and
2. hook into `wcsatt_set_product_subscription_scheme`, so that once the cart items are loaded, and the schemes applied, the cart hash is saved with the updated info. 

The trouble is with 2., because `WCS_Cart_Renewal::set_cart_hash` fires way before any discounts are applied, therefore the cart hash that is saved there are for the non-discounted prices. Then the discounts get applied as per scheme settings, and on checkout the cart hash comparison fails in `WC_Checkout::create_order`.

Mind you this is for Subs 2.0.20 and WC 2.6.14, so it *might* work for WC3 and up to date subs.

**Comment by javorszky** [comment]
The method I hook into the `wcsatt_price_filters_allowed` hook is this:

```php
public function dont_discount_prices_twice_on_failed_resubscribe( $discounts_allowed, $product ) {

	foreach ( WC()->cart->cart_contents as $cart_key => $item_data ) {
		if ( $product->id === wcs_get_canonical_product_id( $item_data ) && ( array_key_exists( 'subscription_renewal', $item_data ) || array_key_exists( 'subscription_resubscribe', $item_data ) ) ) {
			return false;
		}
	}
	return $discounts_allowed;
}
```

**Comment by thenbrent** [comment]
@javorszky almost identical code to that is already in Subscriptions from v2.1.4 onwards: https://github.com/Prospress/woocommerce-subscriptions/commit/3377da989a27760e840c37c814227dac037ddcd6 (introduced in https://github.com/Prospress/woocommerce-subscriptions/pull/1852)

> Mind you this is for Subs 2.0.20

I'd recommend you update. But you already know that. :)

**Comment by javorszky** [comment]
@thenbrent I haven't seen that! :D Yes, we'd like to update, but client, and their cost-averse attitudes towards maintenance. :) Thank you though

**Comment by franticpsyx** [comment]
@javorszky 

Might be wrong, but my feeling is that in order to resolve this, SATT will need to "load" only the subscription scheme that's being renewed/initialized on objects associated with cart items populated via `WCS_Cart_Renewal` or its child classes, _and_ overwrite/delete the discount defined in the set scheme so that it never gets applied.

By default, SATT will display all subscription options in the cart -- this shouldn't be happening when:

- making an initial subscription order, or 
- renewing, or 
- resubscribing.

Basically SATT will need to modify the schemes loaded on the cart item(s) to be consistent with the scheme saved on the subscription order item(s) being handled. Correct? 

If so, then one place to do this would be `WCS_ATT_Cart::apply_subscription_schemes`, which is the final point where scheme data is set/modified on product objects in the cart.

I am not so familiar with WCS internals to have a sufficiently good understanding of how to deal with the cart hash problem just yet, but my understanding is that solving this involves more than preventing discounts from being applied twice.

**Comment by franticpsyx** [comment]
@javorszky -- I think bf7902962f722308eaee69ad548445423210870f should take care of this:

> Basically SATT will need to modify the schemes loaded on the cart item(s) to be consistent with the scheme saved on the subscription order item(s) being handled.

There doesn't seem be anything that prevents me from checking out when renewing/resubscribing. Without digging in deeper, I would say I don't see any cart-hash related issue.

**Comment by rezzz-dev** [comment]
Much like @javorszky I can't upgrade to WCS 2.1 just yet but having 2 issues with the 2.0 branch that seems related to this.

1. If there are 2 products that are subscriptions on the order that fails, when the customer clicks on "Pay", only one gets added to the cart. Seems to be the second line item as well. 

2. The shipping rate for the order doesn't pick up that they are subscriptions and not single time products.

Curious as to your thoughts on this? Or if someone has encountered this yet, especially since it seems there are a few fixes listed in here.

**Comment by franticpsyx** [comment]
@rezzz-dev WCS 2.0 is not supported by SATT 2.0. If you can replicate an issue with WCS 2.1 I can go back and have another look, otherwise there's not much else I can suggest.

Thanks for looking into it!

**Comment by rezzz-dev** [comment]
Understood.
